package constants 
const Connectstring = "mongodb+srv://guru:guru@banking.sy1piq8.mongodb.net/?retryWrites=true&w=majority"
const DB_Name = "Ecommerce"
const Customer_collection = "Coustomer"
const Seller_Collection = "Seller"
const Cart_collection = "Cart"
const Inventory_Collection = "Inventory"
const Feedback_Collection = "Feedback"
const SecretKey = "EcommerceSiteforS7Project"
const AdminSecretKey = "AdminAnonSite"
const BuyItems_Collection = "Buynow"
const Admin_Collection = "Admins"
const Sales_Collection = "Sales"
const Worker_Collection = "Workers"
const Calender_Collection = "Calender"
const ShutDownKey = "AnonShutDown"
